model:
  base_learning_rate: 4.5e-4
  target: sgm.models.autoencoder.AutoencodingEngine
  params:
    input_key: ct_slice
    monitor: val/loss/rec
    disc_start_iter: 0

    encoder_config:
      target: sgm.modules.diffusionmodules.model.Encoder
      params:
        attn_type: vanilla-xformers
        double_z: true
        z_channels: 8
        resolution: 128
        in_channels: 1
        out_ch: 1
        ch: 128
        ch_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0

    decoder_config:
      target: sgm.modules.diffusionmodules.model.Decoder
      params: ${model.params.encoder_config.params}

    regularizer_config:
      target: sgm.modules.autoencoding.regularizers.DiagonalGaussianRegularizer

    loss_config:
      target: sgm.modules.autoencoding.losses.GeneralLPIPSWithDiscriminator
      params:
        perceptual_weight: 0.25
        disc_start: 20001
        disc_weight: 0.5
        learn_logvar: True
        disc_in_channels: 1

        regularization_weights:
          kl_loss: 1.0

data:
  target: sgm.data.radchest.RadchestIndividualCtSlice128Dataloader
  params:
    num_slices: 128
    train:
      loader:
          batch_size: 64
          num_workers: 16
          shuffle: True
      dataset:
        target: sgm.data.radchest.CachedXCT_H5_dataset
        params:
          cache_dir: /raid/maximilian.schulze/dataset_cache
          optimize_zip: True
          h5_dataset_path: /raid/shared/x2ct/radchest/h5/sitk-dataset.h5
          h5_ct_group_path: 512/ct
          h5_xray_group_path: 512/drr
          h5_text_dataset_path: /raid/shared/x2ct/radchest/discription-latents-h5/short-template.h5
          h5_text_group_path: BiomedCLIPTextEmbedder/V2/OneNonNegativeTokens
          split_file: /raid/shared/x2ct/radchest/train_val_split.json
          train: True
          scale: 256
          scale_images: True
          crop_size: 256
          use_f16: False
          ct_only: True
          xray_only: False
          load_text: True
          num_projections: 2
          is_preprocessed: False
    validation:
      loader:
        batch_size: 64
        num_workers: 16
        shuffle: True
      dataset:
        target: sgm.data.radchest.CachedXCT_H5_dataset
        params:
          cache_dir: /raid/maximilian.schulze/dataset_cache
          optimize_zip: True
          h5_dataset_path: /raid/shared/x2ct/radchest/h5/sitk-dataset.h5
          h5_ct_group_path: 512/ct
          h5_xray_group_path: 512/drr
          h5_text_dataset_path: /raid/shared/x2ct/radchest/discription-latents-h5/short-template.h5
          h5_text_group_path: BiomedCLIPTextEmbedder/V2/OneNonNegativeTokens
          split_file: /raid/shared/x2ct/radchest/train_val_split.json
          train: False
          scale: 256
          scale_images: True
          crop_size: 256
          use_f16: False
          ct_only: True
          xray_only: False
          load_text: True
          num_projections: 2
          is_preprocessed: False

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: True

  modelcheckpoint:
    params:
      every_n_train_steps: 2000

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 2000

    image_logger:
      target: main.ImageLogger
      params:
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    devices: 0,
    limit_val_batches: 100
    benchmark: True
    accumulate_grad_batches: 1
    val_check_interval: 0.3333333333333333

projectname: ct-stablediffusion
wandb: True
