model:
  base_learning_rate: 1e-5
  target: sgm.models.diffusion.DiffusionEngine
  params:
    input_key: ct_video
    num_frames: 128
    network_wrapper: sgm.modules.diffusionmodules.wrappers.OpenAIVideoWrapper
    scale_factor: 0.18215
    disable_first_stage_autocast: True
    en_and_decode_n_samples_a_time: 32
    log_keys:
      - xrays
    network_dtype: bfloat16

    # scheduler_config:
    #   target: sgm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [200]
    #     cycle_lengths: [10000000000000]
    #     f_start: [1.e-4]
    #     f_max: [1.]
    #     f_min: [1.]

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.Denoiser
      params:
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.VScalingWithEDMcNoise

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:
        batch2model_keys:
          - image_only_indicator
        loss_weighting_config:
          target: sgm.modules.diffusionmodules.loss_weighting.EpsWeighting
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.DiscreteSampling
          params:
            num_idx: 1000

            discretization_config:
              target: sgm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization

    network_config:
      target: sgm.modules.diffusionmodules.video_model.VideoUNet
      params:
        adm_in_channels: 256
        num_classes: sequential
        use_checkpoint: True
        in_channels: 24 # 8 ct + 8 xray 1 + 8 xray 2
        out_channels: 8
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 512
        spatial_transformer_attn_type: softmax-xformers
        extra_ff_mix_layer: True
        use_spatial_context: True
        merge_strategy: learned_with_images
        video_kernel_size: [3, 1, 1]

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
        - input_key: xrays # crossattn (dims=3)
          is_trainable: False
          target: sgm.modules.encoders.modules.FrozenOpenCLIPImagePredictionEmbedderXrays
          params:
            open_clip_embedding_config:
              target: sgm.modules.encoders.modules.FrozenOpenCLIPImageEmbedderMedical
              params: {}

        - input_key: xrays # concat (dims=4)
          is_trainable: False
          target: sgm.modules.encoders.modules.VideoPredictionEmbedderWithEncoder
          params:
            disable_encoder_autocast: True
            n_cond_frames: 2
            n_copies: 1 # Number of frames to generate
            is_ae: True
            encoder_config:
              target: sgm.models.autoencoder.AutoencodingEngine
              params:
                ckpt_engine: /home/maximilian.schulze/generative-models/logs/2025-03-20T21-39-55_x2ct_ct_rate-xray-imagenet-kl_f8_8chn-xray-128/checkpoints/last.ckpt
                loss_config:
                  target: torch.nn.Identity
                regularizer_config:
                  target: sgm.modules.autoencoding.regularizers.DiagonalGaussianRegularizer
                encoder_config:
                  target: sgm.modules.diffusionmodules.model.Encoder
                  params:
                    attn_type: vanilla-xformers
                    double_z: true
                    z_channels: 8
                    resolution: 128
                    in_channels: 1
                    out_ch: 1
                    ch: 128
                    ch_mult: [1, 2, 4, 4]
                    num_res_blocks: 2
                    attn_resolutions: []
                    dropout: 0.0
                decoder_config:
                  target: sgm.modules.diffusionmodules.model.Decoder
                  params:
                    attn_type: vanilla-xformers
                    double_z: true
                    z_channels: 8
                    resolution: 128
                    in_channels: 1
                    out_ch: 1
                    ch: 128
                    ch_mult: [1, 2, 4, 4]
                    num_res_blocks: 2
                    attn_resolutions: []
                    dropout: 0.0

        - is_trainable: True
          input_key: raw_text
          target: sgm.modules.encoders.modules.TrainableConditioningProjection
          params:
            input_dim: 768
            output_dim: 512
            freeze_model: true
            model:
              target: sgm.modules.encoders.modules.FrozenOpenCLIPEmbedderMedical
              params:
                freeze: true
                layer: last # penultimate

        - input_key: cond_aug
          is_trainable: False
          target: sgm.modules.encoders.modules.ConcatTimestepEmbedderNDCT
          params:
            outdim: 256

    first_stage_config:
      target: sgm.models.autoencoder.AutoencodingEngine
      params:
        ckpt_engine: /home/maximilian.schulze/generative-models/logs/2025-03-21T01-05-16_x2ct_ct_rate-ct-imagenet-kl_f8_8chn-ct-stacked128/checkpoints/trainstep_checkpoints/eepoch=000004-sstep=000186000-train/loss/rec=train/loss/rec=0.08820.ckpt
        loss_config:
          target: torch.nn.Identity
        regularizer_config:
          target: sgm.modules.autoencoding.regularizers.DiagonalGaussianRegularizer
        encoder_config:
          target: sgm.modules.diffusionmodules.model.Encoder
          params:
            attn_type: vanilla-xformers
            double_z: true
            z_channels: 8
            resolution: 128
            in_channels: 1
            out_ch: 1
            ch: 128
            ch_mult: [1, 2, 4, 4]
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0
        decoder_config:
          target: sgm.modules.diffusionmodules.model.Decoder
          params: ${model.params.first_stage_config.params.encoder_config.params}

    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 32
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.EDMDiscretization
          params:
            sigma_max: 700.0

        guider_config:
          target: sgm.modules.diffusionmodules.guiders.TrianglePredictionGuider
          params:
            max_scale: 2.5
            num_frames: 128

data:
  target: sgm.data.ct_rate.CTVideo128Dataloader
  params:
    num_slices: 128
    # condition_cache_path: cache/sv3d256notext
    train:
      loader:
        batch_size: 6
        num_workers: 24
        shuffle: True
      dataset:
        target: x2ct_datasets.ct_rate.dataset.CTRATEDatasetWithText
        params:
          split: train
          load_ct: true
          load_xray: true
          downsample_size: 128
          output_dtype: float32
    validation:
      loader:
          batch_size: 6
          num_workers: 24
          shuffle: False
      dataset:
        target: x2ct_datasets.ct_rate.dataset.CTRATEDatasetWithText
        params:
          split: val
          load_ct: true
          load_xray: true
          downsample_size: 128
          output_dtype: float32


lightning: # lightning_config
  modelcheckpoint: # Checkpointing based on monitoring
    params:
      every_n_train_steps: 300
      save_on_train_epoch_end: True

  trainer: # trainer_config
    devices: 0,
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 2
    max_epochs: 1000
    # strategy: "deepspeed_stage_3"
    precision: '32-true'
    # Validation takes a long time - only run validation step on one batch
    limit_val_batches: 1
    val_check_interval: 0.5 # Every half an epoch
  
  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 5000

    image_logger:
      target: main.ImageLogger
      params:
        disabled: False
        batch_frequency: 1000
        max_images: 64
        increase_log_steps: True
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          N: 64
          n_rows: 8
